// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pglopgkhlgjszerbhhpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnbG9wZ2tobGdqc3plcmJoaHBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjg0MDUsImV4cCI6MjA2MDg0NDQwNX0.Y4gzIdjksL-2DT1_l17lkivxD63B05gRnJFAmSQQEIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);